Added `--max-warnings` option
IBM/tekton-lint pull request #12
Opened 2020-10-07 09:01 UTC by tamasmuncsan

If `--max-warnings` option which can be used to specify a threshold for the number of warnings.
If the number of warnings is over the specified number, the exit code will be `1`.
If the value of the option is not a number, the CLI exits with an error.

Resolves https://github.com/IBM/tekton-lint/issues/9

2020-10-07 09:22 UTC, edinapap approved these changes

2020-10-08 21:56 UTC, madbence requested changes

2020-10-08 21:56 UTC, madbence commented on lint.js
> +$ tekton-lint --max-warnings <Int>   # Number of warnings to trigger nonzero exit code - default: -1
looks like `-1` is not a valid option here: `Invalid value for 'max-warnings' option. Expected a number, received value: true.`

2020-10-09 07:15 UTC, tamasmuncsan commented on lint.js
> +$ tekton-lint --max-warnings <Int>   # Number of warnings to trigger nonzero exit code - default: -1
This is an issue with `minimist`.
https://github.com/substack/minimist/issues/117

2020-10-09 08:39 UTC, madbence commented on lint.js
> +$ tekton-lint --max-warnings <Int>   # Number of warnings to trigger nonzero exit code - default: -1
I see... well, that's a bit annoying, but I don't think that that's a huge issue, let's merge this!

2020-10-09 08:39 UTC, merged