Fixes for array arguments to tasks and images in stepTemplates
IBM/tekton-lint pull request #21
Opened 2020-10-14 03:02 UTC by bhartshorn

The following task inside a pipeline causes tekton-lint to crash:
```
    - name: shellcheck-run
      taskRef:
        name: shellcheck
      runAfter:
        - clone-repo
      workspaces:
        - name: shared-workspace
          workspace: pipeline-pvc
      params:
        - name: shellcheck-args
          value: ["--color=always"]
```

or

```
        - name: shellcheck-args
          value:
            - "--color=always"
```

the `shellcheck-args` parameter causes the following error:

```
TypeError: value.match is not a function
    at readParamReference (/src/rules/no-pipeline-task-cycle.js:6:14)
    at /src/rules/no-pipeline-task-cycle.js:18:8
    at Array.map (<anonymous>)
    at paramsReferences (/src/rules/no-pipeline-task-cycle.js:17:17)
    at buildTaskGraph (/src/rules/no-pipeline-task-cycle.js:55:35)
    at errorCyclesInPipeline (/src/rules/no-pipeline-task-cycle.js:67:29)
    at module.exports (/src/rules/no-pipeline-task-cycle.js:78:5)
    at Object.lint (/src/rules.js:52:5)
    at AsyncFunction.lint (/src/runner.js:32:16)
    at runner (/src/runner.js:26:25)
```

There are other ways to solve this than using `toString()`, I'm happy to switch if there's an argument against it. (https://stackoverflow.com/a/27626619)

---

Next up, tekton-lint was crashing on a task definition where the `image` was specified in the stepTemplate and the step didn't have an `image` key.

This should probably result in an additional rule which ensures `image` is in step template if a step doesn't specify an `image`, but it's outside scope of the `no-latest-image` rule.

2020-10-14 06:28 UTC, tamasmuncsan requested changes

2020-10-14 06:28 UTC, tamasmuncsan commented on rules/no-pipeline-task-cycle.js
> +  if (!value.toString().match(taskResultReferenceRegexp)) return;
In case of referencing a Task Result inside of an array, this check will fail. What do you think about iterating through the `value` if it's an array and checking each element for a Task Result reference?

2020-10-14 06:28 UTC, tamasmuncsan commented on rules/no-pipeline-task-cycle.js
> +  if (!value.toString().match(taskResultReferenceRegexp)) return;
example: 
```yaml
    - name: shellcheck-run
      taskRef:
        name: shellcheck
      runAfter:
        - clone-repo
      workspaces:
        - name: shared-workspace
          workspace: pipeline-pvc
      params:
        - name: shellcheck-args
          value: ["--color=always", "$(tasks.my-task.results.my-result)"]
```

2020-10-14 18:39 UTC, bhartshorn commented on rules/no-pipeline-task-cycle.js
> +  if (!value.toString().match(taskResultReferenceRegexp)) return;
> referencing a Task Result inside of an array

Yeah, I didn't think of that - honestly a little surprised that it's supported, but it makes sense. I'll give it a go!

2020-10-16 12:52 UTC, tamasmuncsan commented on rules/no-pipeline-task-cycle.js
> +  if (!value.toString().match(taskResultReferenceRegexp)) return;
I've tested it with Tekton `v0.16.3` and turns out It's supported, but could not find any examples in the [tektoncd/pipeline](https://github.com/tektoncd/pipeline) repository.
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
  tasks:
    - name: echo-task-run
      taskRef:
        name: echo
      params:
        - name: values
          value:
            - 'value-1'
            - 'value-2'
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  params:
    - name: values
       type: array
  steps:
    - image: alpine
      command: ["echo"]
      args: ["$(params.values[*])"]

```

2020-10-18 20:24 UTC, madbence commented
@bhartshorn thanks! I created a separate PR to address the `image` issue (#24), and updated the parsing logic in the `no-pipeline-task-cycle` rule. The example you provided now passes!

2020-10-18 20:24 UTC, merged

2020-10-18 20:34 UTC, madbence commented
I published `tekton-lint@0.4.4`!