feat: process exit on no tekton-definition
IBM/tekton-lint pull request #27
Opened 2020-10-19 15:27 UTC by markkovari

refs: #20 

When there are no tekton-definitions with the given paths, the linter should exit with `1` as error code.

2020-10-19 16:06 UTC, edinapap requested changes

2020-10-19 16:40 UTC, tamasmuncsan requested changes

2020-10-19 16:40 UTC, tamasmuncsan commented on src/rules.ts
> +    process.exit(1);
I do not think this file should handle the process. What do you think about throwing an error instead?

2020-10-19 16:40 UTC, tamasmuncsan commented on regression-tests/regresion.test.js
> +it('the linter with a path, that contains no definition should write to stderr and return 1 as exit code', async () => {
This test may not be a `regression` test, this is more like a `unit` test in my opinion, and we should not mix them.

2020-10-20 10:47 UTC, markkovari commented on src/rules.ts
> +    process.exit(1);
<img width="915" alt="Screenshot 2020-10-20 at 12 46 59" src="https://user-images.githubusercontent.com/33259514/96576348-59906700-12d2-11eb-879e-cc939ddc9719.png">
In that case it would look something like this. If we are not handling the errors differently somehow.
🤔

2020-10-20 10:52 UTC, markkovari commented on src/rules.ts
> +    process.exit(1);
But yeah, makes sense, thanks to point out

2020-10-21 20:13 UTC, merged