fix: add check for duplicate params within task spec
IBM/tekton-lint pull request #46
Opened 2020-10-26 14:14 UTC by tonymaynard

2020-10-27 21:31 UTC, madbence requested changes
Thanks for the contribution @tonymaynard! 🎉 

I added a couple of comments, can you fix those issues?

2020-10-27 21:31 UTC, madbence commented on src/rules/no-duplicate-param.ts
> +    }
looks like indentation is a bit messed up, `checkParams` on line 24 should be indented a bit further.

what do you think about using `for..of` instead of `forEach`? We're using the former all over the codebase, and I'd encourage everyone to use it: it's idiomatic JavaScript, with several benefits over `forEach` (eg. works with `Iterable`s, not just `Array`s)

the first parameter of `getParams` is `kind`, which refers to the [k8s kind](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/) of the object, so it should be `Task` in case of tasks, and not `taskSpec`, or `task.name`.

2020-10-28 08:33 UTC, tonymaynard commented on src/rules/no-duplicate-param.ts
> +    }
You must've read my mind, I was planning to change it to a `for..of` instead of `forEach` No problem I shall look into changing the first param too :)

2020-10-29 10:51 UTC, madbence commented
@tonymaynard i see that you linked #39, are you sure that it resolves it? based on the code, it's related to #38, which was resolved in #49

2020-10-29 11:05 UTC, tonymaynard commented
> @tonymaynard i see that you linked #39, are you sure that it resolves it? based on the code, it's related to #38, which was resolved in #49

I See someone beat me too it :/ no matter

2020-12-15 14:30 UTC, closed without merging